# -*- coding: utf-8 -*-
"""Preprocessing Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NFJPPCgq4lSZsr87OrTGXI4_yb8lEagO
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Numpy digunakan untuk komputasi matriks.

"""

dataset = pd.read_csv('DaftarNama.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(x)

print(y)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

from sklearn.compose import ColumnTransformer
from sklearn.preprocesing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder=)
x= np.array(ct.fit_transform(x))

print (x)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print (y)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, Y_test = train_test_split(x, y, test_size=0,2, random_state=1)

print(x_train)

print(y_train)

print (y_test)

from sklearn.preprocessing import StandardScaler
sc = StandartScaler
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

print (x_train)

print (x_test)